version: "3.9"

services:
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./log/caddy:/var/log/caddy
      - ./app/blank:/srv
      - caddy_data:/data
      - caddy_config:/config

  v2ray:
    image: "v2fly/v2fly-core:${TAG_V2FLY_CORE}"
    restart: unless-stopped
    ports:
      - "38202"
    command:
      - run
      - -c
      - /etc/v2ray/config.json
    volumes:
      - ./config/v2ray/vless_grpc_loopback.json:/etc/v2ray/config.json
      - ./log/v2ray:/var/log/v2ray

volumes:
  caddy_data:
    external: true
  caddy_config:
