dockers:

  caddy:
    template: templates/services/caddy.yml.jinja
    volume_template: templates/volumes/caddy.yml.jinja
    config_template: templates/configs/caddy/caddy.json.jinja
    tls:
      wildcard: false
      acme_dns: cloudflare

  blog:
    enabled: true

  xray:
    enabled: true
    template: templates/services/xray.yml.jinja
    scheme: reality_vision_with_caddy
    config_template:
      vless_grpc_loopback: templates/configs/xray/vless_grpc_loopback.json.jinja
      reality_vision_with_caddy: templates/configs/xray/reality_vision_with_caddy.json.jinja

  freshrss:
    enabled: true
    template: templates/services/freshrss.yml.jinja
    volume_template: templates/volumes/freshrss.yml.jinja
    config_template: templates/configs/freshrss/config.custom.php.jinja

    language: 'zh-cn'
    development: true
    cron: "3,23,43"

  memos:
    enabled: true
    template: templates/services/memos.yml.jinja

  remark42:
    enabled: true
    template: templates/services/remark42.yml.jinja
    anonymous_login: true
